[package]
name = "kernel"
version = "0.1.1"
authors = ["Maxim Sokhatskyi <maxim@synrc.com>"]
license = "MIT"
repository = "https://github.com/voxoz/kernel"
homepage = "https://github.com/voxoz/kernel"
documentation = "http://5ht.co/kernel.htm"
description = """
Abstract Reactive Streams
"""

[[bin]]
name = "echo"
path = "src/apps/echo.rs"

[dependencies]
log = "0.3"
mio = "0.6"
slab = "0.3"
